studyportal/dashboard/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name = 'home'),
    
    path('notes/', notes, name = 'notes'),
    path('delete-note/<int:pk>', delete_note, name = 'delete-note'),
    path('note-info/<int:pk>', note_info, name = 'note-info'),
    # path('notes-detail/<int:pk>', note_details.as_view(), name = 'notes-detail'),
    
    path('homework/', homework, name = 'homework'),
    path('update-homework/<int:pk>', update_hw, name = 'update-homework'),
    path('delete-homework/<int:pk>', delete_hw, name = 'delete-homework'),
    
    path('youtube/', youtube, name = 'youtube'),
    
    path('todo/', todo, name = 'todo'),
    path('update-todo/<int:pk>', update_todo, name = 'update-todo'),
    path('delete-todo/<int:pk>', delete_todo, name = 'delete-todo'),
]

studyportal/studyportal/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard.views import register, profile
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('register/', register, name = 'register'),
    path('login/', auth_views.LoginView.as_view(template_name = 'dashboard/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'dashboard/logout.html'), name='logout'),
    path('profile/', profile, name = 'profile'),
]

studyportal/dashboard/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Notes(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()

    class Meta:
        verbose_name = 'notes'
        verbose_name_plural = 'notes'

    def __str__(self):
        return self.title
    

class Homework(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    subject = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    due = models.DateField()
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.subject


class ToDo(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length=50)
    time = models.TimeField()
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Todo'
        verbose_name_plural = 'Todo'

    def __str__(self):
        return self.title

studyportal/dashboard/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm

class NoteForm(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ['title','description']


class DateInput(forms.DateInput):
    input_type = 'date'


class HomeworkForm(forms.ModelForm):
    class Meta:
        model = Homework
        widgets = {'due': DateInput()}
        fields = ['subject', 'title', 'description',
                 'due', 'status']
        

class DashboardForm(forms.Form):
    text = forms.CharField(max_length=100, label='Enter your seach ')


class TodoForm(forms.ModelForm):
    class Meta:
        model = ToDo
        widgets = {
            'time': forms.TimeInput(attrs={'type': 'time'}),
        }
        fields = ['title', 'time', 'status']


class UserRegistration(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','password1','password2']

studyportal/dashboard/views.py
from django.shortcuts import render, redirect
from .models import Notes
from django.contrib import messages
from .forms import *
from django.views import generic
from youtubesearchpython import VideosSearch
from django.contrib.auth.decorators import login_required

# Create your views here.

def home(request):
    return render(request, 'dashboard/home.html')



@login_required
def notes(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            title = request.POST.get('title')
            description = request.POST.get('description')
            notes = Notes(user = request.user, title = title, description = description)
            notes.save()       
        messages.success(request, f'Notes added from {request.user.username} succesfully')
        return redirect('/notes/')

    form = NoteForm()
    note = Notes.objects.filter(user = request.user)
    return render(request, 'dashboard/notes.html', context = {'Notes': note, 'form': form})


@login_required
def delete_note(request, pk=None):
    Notes.objects.get(id=pk).delete()
    return redirect('/notes/')


@login_required
def note_info(request, pk):
    note = Notes.objects.get(id=pk)
    referer = request.META.get('HTTP_REFERER', '/')
    return render(request, 'dashboard/notes_detail.html', context={'notes': note, 'referer': referer})

# class note_details(generic.DetailView):
#     model = Notes


@login_required
def homework(request):
    if request.method == 'POST':
        form = HomeworkForm(request.POST)
        if form.is_valid():
            try:
                finished = request.POST.get('status')
                if finished == 'on':
                    finished = True
                else:
                    finished = False
            except:
                finished = False
            
            user = request.user
            subject = request.POST.get('subject')
            title = request.POST.get('title')
            description = request.POST.get('description')
            due = request.POST.get('due')
            hw = Homework(user=user, subject=subject, title=title, description=description, due=due, status=finished)
            hw.save()

        messages.success(request, f'Homework added from {request.user.username} succesfully')
        return redirect('/homework/')

    form = HomeworkForm()
    hw = Homework.objects.filter(user=request.user)
    if len(hw) == 0:
        hw_done = True
    else:
        hw_done = False
    
    context = {
        'homework' : hw, 
        'hw_done' : hw_done, 
        'form' : form
    }
    return render(request,'dashboard/homework.html', context = context)


@login_required
def update_hw(request, pk=None):
    hw = Homework.objects.get(id=pk)
    if hw.status == True:
        hw.status = False
    else:
        hw.status = True
    hw.save()

    return redirect('/homework/')


@login_required
def delete_hw(request, pk=None):
    Homework.objects.get(id=pk).delete()
    return redirect('/homework/')



def youtube(request):
    if request.method == 'POST':
        form = DashboardForm(request.POST)
        text = request.POST.get('text')
        video = VideosSearch(text, limit=10)
        result_list = []
        for i in video.result()['result']:
            result_dict = {
                'input' : text,
                'title' : i['title'],
                'duration' : i['duration'],
                'thumbnail' : i['thumbnails'][0]['url'],
                'channel' : i['channel']['name'],
                'link' : i['link'],
                'viewcount' : i['viewCount']['short'],
                'published' : i['publishedTime']
            }
            desc = ''
            if i['descriptionSnippet']:
                for j in i['descriptionSnippet']:
                    desc += j['text']
            result_dict['description'] = desc
            result_list.append(result_dict)

            context={
                'form': form,
                'results': result_list
            }
        
        return render(request, 'dashboard/youtube.html', context=context)
    
    form = DashboardForm()
    context={'form': form}
    return render(request, 'dashboard/youtube.html', context=context)


@login_required
def todo(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            try:
                finished = request.POST.get('status')
                if finished == 'on':
                    finished = True
                else:
                    finished = False
            except:
                finished = False
            
            user = request.user
            title = request.POST.get('title')
            time = request.POST.get('time')
            todo = ToDo(user=user, title=title, time=time, status=finished)
            todo.save()
        
        messages.success(request, f'Todo item added from {request.user.username} succesfully')
        return redirect('/todo/')

    form = TodoForm()
    todo = ToDo.objects.filter(user=request.user).order_by('time')
    if len(todo) == 0:
        todo_done = True
    else:
        todo_done = False
    
    context = {
        'Todo' : todo, 
        'todo_done' : todo_done, 
        'form' : form
    }
    return render(request,'dashboard/todo.html', context=context)


@login_required
def update_todo(request, pk=None):
    todo = ToDo.objects.get(id=pk)
    if todo.status == True:
        todo.status = False
    else:
        todo.status = True
    todo.save()
    referer = request.META.get('HTTP_REFERER', '/')
    # url = request.url
    print(referer)

    return redirect('/todo/')


@login_required
def delete_todo(request, pk=None):
    ToDo.objects.get(id=pk).delete()
    return redirect('/todo/')



def register(request):
    if request.method == 'POST':
        form = UserRegistration(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Accounted cretaed for {username}')
        return redirect('/login/')

    form = UserRegistration()
    context={'form': form}
    return render(request, 'dashboard/register.html', context=context)

 
@login_required
def profile(request):
    todo = ToDo.objects.filter(user = request.user, status = False).order_by('time')
    if len(todo) == 0:
        todo_done = True
    else:
        todo_done = False

    hw = Homework.objects.filter(user = request.user, status = False)
    if len(hw) == 0:
        hw_done = True
    else:
        hw_done = False

    context = {
        'Todo' : todo, 
        'todo_done' : todo_done,
        'homework' : hw, 
        'hw_done' : hw_done
    }
    return render(request, 'dashboard/profile.html', context=context)

studyportal/dashboard/templates/dashboard/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>Student-dashboard</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
    integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous" />
  <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home'%}">Student Study Portal</a>        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
          <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'profile' %}">Profile</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Options
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'youtube' %}">Youtube</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'todo' %}">To-do</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'homework' %}">Homework</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'notes' %}">Notes</a>
              </div>
            </li>

              <li class="nav-item">
                <a class="nav-link" href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                  Logout
                </a>
              </li>
              <form id="logout-form" action="{% url 'logout' %}" method="POST" style="display: none;">
                  {% csrf_token %}
              </form>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <br /><br />
  <main>

  <div class="container">
    {% if messages%}
      {% for msg in messages %}
        <div class="alert alert-{{msg.tags}}">{{msg}}</div>
      {% endfor %}
    {% endif %}
  </div>

    {% block content %}
    {% endblock content %}

  </main>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
</body>

</html>

studyportal/dashboard/templates/dashboard/home.html
{% extends 'dashboard/base.html' %} 
{% load static %} 
{% block content %}

<section class="container text-center">
  <h2>Welcome</h2>

  <hr> <br>
  <div class="row">
    <div class="col-md-3">
      <a href="{% url 'notes'%}">
        <div class="card">
          <img class="card-img-top" src="{% static 'images/notes.jpg' %}" alt="Notes image">
          <div class="card-body">
            <h5 class="card-title ">
              Notes
            </h5>
            Create Notes to refer them later. They are stored permanently until deleted
          </div>
        </div>
      </a>
    </div>

    <div class="col-md-3">
      <a href="{% url 'homework'%}">
        <div class="card">
          <img class="card-img-top" src="{% static 'images/homework.jpg' %}" alt="Notes image">
          <div class="card-body">
            <h5 class="card-title ">
              Homework
            </h5>
            Add homeworks and assign them deadlines. They will be displayed prioritised by deadlines
          </div>
        </div>
      </a>
    </div>

    <div class="col-md-3">
      <a href="{% url 'youtube' %}">
        <div class="card">
          <img class="card-img-top" src="{% static 'images/youtube.jpg' %}" alt="Notes image">
          <div class="card-body">
            <h5 class="card-title ">
              Youtube
            </h5>
            Search Youtube and select your desired video to play it on youtube
          </div>
        </div>
      </a>
    </div>

    <div class="col-md-3">
      <a href="{% url 'todo' %}">
        <div class="card">
          <img class="card-img-top" src="{% static 'images/todo.jpg' %}" alt="Notes image">
          <div class="card-body">
            <h5 class="card-title ">
              To Do
            </h5>
            Add your to-do lists for your day and remove them as you finish
          </div>
        </div>
      </a>
    </div>
  </div>

  <br><br><br>

  <!-- <div class="row">
    <div class="col-md-3 ">
      <a href="#">
        <div class="card mt-20">
          <img class="card-img-top" src="{% static 'images/books.jpg' %}" alt="Notes image">
          <div class="card-body">
            <h5 class="card-title ">
              Books
            </h5>
            Browse books from a list of neatly organised book menu
          </div>
        </div>
      </a>
    </div>

    <div class="col-md-3">
      <a href="#">
        <div class="card">
          <img class="card-img-top" src="{% static 'images/dictionary.jpg' %}" alt="Notes image">
          <div class="card-body">
            <h5 class="card-title ">
              Dictionary
            </h5>
            A vocabulary from a book is troubling you? No problem, enter the word, and the meaning will be displayed
            almost instantaneously.
          </div>
        </div>
      </a>
    </div> -->

    <!-- <div class="col-md-3">
      <a href="#">
        <div class="card">
          <img class="card-img-top" src="{% static 'images/wiki.jpg' %}" alt="Notes image">
          <div class="card-body">
            <h5 class="card-title ">
              WikiPedia
            </h5>
            Homework and Assignments? Search wikipedia to get fast results
          </div>
        </div>
      </a>
    </div>


    <div class="col-md-3">
      <a href="#">
        <div class="card">
          <img class="card-img-top" src="{% static 'images/conversion.jpg' %}" alt="Notes image">
          <div class="card-body">
            <h5 class="card-title ">
              Conversion
            </h5>
            Check out the conversion table, that helps you to convert measurements to more familiar ones of your choice.
          </div>
        </div>
      </a>
    </div>
  </div> -->


</section>
{% endblock content %}

studyportal/dashboard/templates/dashboard/homework.html
{% extends 'dashboard/base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    {% if not hw_done %}
        <table class="table table-striped table-bordered table-hover table-dark">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Due</th>
                    <th scope="col">Status</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for hw in homework %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{hw.subject}}</td>
                    <td>{{hw.title}}</td>
                    <td>{{hw.description}}</td>
                    <td>{{hw.due}}</td>

                    <td>
                        <a href="{% url 'update-homework' hw.id %}">
                            <div class="form-check">
                                {% if hw.status %}
                                    <input class="form-check-input" type="checkbox" value="" checked>
                                {% else %}
                                    <input class="form-check-input" type="checkbox" value="">
                                {% endif %}
                                <label class="form-check-label text-light" for="flexCheckDefault">
                                    Mark as Completed
                                </label>
                            </div>
                        </a>
                    </td>
                    <td><a href="{% url 'delete-homework' hw.id %}"><i class="fa fa-trash fa-2x"></i></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <!-- <h4>Homeworks is not completed!!</h4> -->
    {% else %}
        <h4>All homeworks are completed!!</h4>
    {% endif %}
</div>

<br><br>

<div class=" container">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create Homework</legend>
        </fieldset>
        {{form|crispy}}
        <div class="form-group">
            <button href="" class="btn btn-outline-info" type="submit">
                Create
            </button>
        </div>
    </form>
</div>
{% endblock content %}

studyportal/dashboard/templates/dashboard/login.html
{% extends 'dashboard/base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Log In</legend>
    </fieldset>
    {{form|crispy}}
    <div class="form-group">
      <button href="" class="btn btn-outline-info" type="submit">
        Sign In
      </button>
    </div>
  </form>
  <div class="border-top pt-3">
    <small class="text-muted">Need an Account?
      <a class="ml-2" href="{% url 'register' %}">Create an Account</a>
    </small>
  </div>
</div>

{% endblock content %} 

studyportal/dashboard/templates/dashboard/logout.html
{% extends 'dashboard/base.html' %} 
{% load static %}
{% block content %}

<div class="border-top pt-3 text-center">
  <form method="POST">
    {% csrf_token %}
    <h2>You are logged Out</h2>

    <small class="text-muted"
      ><a class="btn btn-danger" href="{% url 'login' %}">Log In Again</a>
    </small>
  </form>
</div>

{% endblock content %} 

studyportal/dashboard/templates/dashboard/notes.html
{% extends 'dashboard/base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row">
        {% for note in Notes %}
        <div class="col-md-3  mb-4">
            <a href="{% url 'note-info' note.id %}">
                <div class="card">
                    <h3 class="card-header">{{note.title}}</h3>
                    <div class="card-body">{{note.description|slice:"0:100"}}</div>
                    <div class="card-footer mt-auto "><a href="{% url 'delete-note' note.id %}">
                        <i class="fa fa-trash fa-2x"></i></a>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}

        <br><br>

    </div>
</div>
<br><br>
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create Notes</legend>
        </fieldset>
        <!-- {{form|crispy}} -->

        <div class="form-group">
            <label for="id_title">Title*</label>
            <input type="text" class="form-control" id="id_title" required name="title" value="{{ form.title.value|default:'' }}">
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    {{ form.title.errors }}
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="id_description">Description*</label>
            <textarea class="form-control" id="id_description" required name="description">{{ form.description.value|default:'' }}</textarea>
            {% if form.description.errors %}
                <div class="alert alert-danger">
                    {{ form.description.errors }}
                </div>
            {% endif %}
        </div>
    

        <div class="form-group">
            <button href="" class="btn btn-outline-info" type="submit">
                Create
            </button>
        </div>

    </form>
</div>

{% endblock content %} 

studyportal/dashboard/templates/dashboard/notes_detail.html
{% extends 'dashboard/base.html' %} 
{% load static %} 
{% block content %}

<section class='text-center container'>

    <div class="container">

        <div class="content-section p-0 mt-5">

            <div class="m-3">
                <h2>{{notes.title}}</h2>
            </div>

            <hr class="p-0 m-0">
            <p class="m-2">
                {{notes.description}}
            </p>
            <hr>
        </div>

    </div>

    <div class="form-group">
        <a href="{{ referer }}" class="btn btn-outline-info">
            Back
        </a>
    </div>

</section>

{% endblock content %}

studyportal/dashboard/templates/dashboard/profile.html
{% extends 'dashboard/base.html' %} {% load static %}
{% load crispy_forms_tags%}
{% block content %}
<section class="text-center">

    <div class="container">

        {% if not todo_done %}
        <h2>Due ToDos</h2>
        <table class="table table-striped table-bordered table-hover table-dark">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Time</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
                {% for todo in Todo %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{todo.title}}</td>
                    <td>{{todo.time}}</td>
                    <td>
                        <a href="{% url 'update-todo' todo.id %}">
                            <div class="form-check">
                                {% if todo.status %}
                                    <input class="form-check-input" type="checkbox" value="" checked>
                                {% else %}
                                    <input class="form-check-input" type="checkbox" value="">
                                {% endif %}
                                <label class="form-check-label text-light" for="flexCheckDefault">
                                    Mark as Completed
                                </label>
                            </div>
                        </a>
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            <h3>All To dos are completed!!!!</h3>
        {% endif %}

        <a href="{% url 'todo' %}" class="btn btn-danger">To Do</a>

        <br><br>

        {% if not hw_done %}
        <h2>Due Homeworks</h2>
        <table class="table table-striped table-bordered table-hover table-dark">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Due</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
                {% for hw in homework %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{hw.subject}}</td>
                    <td>{{hw.title}}</td>
                    <td>{{hw.description}}</td>
                    <td>{{hw.due}}</td>

                    <td>
                        <a href="{% url 'update-homework' hw.id %}">
                            <div class="form-check">
                                {% if hw.status %}
                                    <input class="form-check-input" type="checkbox" value="" checked>
                                {% else %}
                                    <input class="form-check-input" type="checkbox" value="">
                                {% endif %}
                                <label class="form-check-label text-light" for="flexCheckDefault">
                                    Mark as Completed
                                </label>
                            </div>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            <h3>All To homeworks are completed!!!!</h3>
        {% endif %}

        <a href="{% url 'homework' %}" class="btn btn-danger">Homeworks</a>
    </div>
</section>

{% endblock content %}

studyportal/dashboard/templates/dashboard/register.html
{% extends 'dashboard/base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Join Today</legend>
      {{form|crispy}}
    </fieldset>
    <div class="form-group">
      <button href="" class="btn btn-outline-info" type="submit">
        Sign Up
      </button>
    </div>
  </form>
  <div class="border-top pt-3">
    <small class="text-muted">Already have an account?
      <a class="ml-2" href="{% url 'login' %}">Sign In</a>
    </small>
  </div>
</div>

{% endblock content %} 

studyportal/dashboard/templates/dashboard/todo.html
{% extends 'dashboard/base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    {% if not todo_done %}
    <table class="table table-striped table-bordered table-hover table-dark">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Time</th>
                <th scope="col">Status</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for todo in Todo %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{todo.title}}</td>
                <td>{{todo.time}}</td>
                <td>
                    <a href="{% url 'update-todo' todo.id %}">
                        <div class="form-check">
                            {% if todo.status %}
                                <input class="form-check-input" type="checkbox" value="" checked>
                            {% else %}
                                <input class="form-check-input" type="checkbox" value="">
                            {% endif %}
                            <label class="form-check-label text-light" for="flexCheckDefault">
                                Mark as Completed
                            </label>
                        </div>
                    </a>
                </td>

                <td><a href="{% url 'delete-todo' todo.id %}"><i class="fa fa-trash fa-2x"></i></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <h4>All tasks have been done!! create to add more</h4>
    {% endif %}
</div>

<br><br>

<div class="container">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create Todo</legend>
        </fieldset>
        {{form|crispy}}
        <div class="form-group">
            <button href="" class="btn btn-outline-info" type="submit">
                Create
            </button>
        </div>
    </form>
</div>

{% endblock content %}